#!/bin/bash
set -e

if [ "$1" != "" ] && [ "$1" = "-h" ]; then
    echo "Shipyard Deploy uses the following environment variables:"
    echo "  PROVIDER: this selects which provider to use with Docker Machine"
    echo "  ACTION: this is the action to use (install, upgrade, node, destroy)"
    echo "  IMAGE: this overrides the default Shipyard image"
    echo "  MACHINE_ARGS: these are passed to Docker Machine during machine creation"
    echo "  SHIPYARD_ARGS: these are passed to the Shipyard controller container as controller args"
    exit 1
fi

if [ -z "`which docker`" ]; then
    echo "You must have the Docker CLI installed on your \$PATH"
    echo "  See http://docs.docker.com for details"
    exit 1
fi

if [ -z "`which docker-machine`" ]; then
    echo "You must have Docker Machine installed on your \$PATH"
    echo "  See http://docs.docker.com/machine for details"
    exit 1
fi

ACTION=${ACTION:-install}
PROVIDER=${PROVIDER:-virtualbox}
IMAGE=${IMAGE:-ehazlett/shipyard:v3}
SHIPYARD_ARGS=${SHIPYARD_ARGS:-""}
HOST_CERT_PATH="/etc/docker"
MACHINE_ARGS=${MACHINE_ARGS:-""}

if [ "$PROVIDER" = "virtualbox" ]; then
    HOST_CERT_PATH="/var/lib/boot2docker"
fi

deploy_shipyard_controller() {
    docker $(docker-machine config shipyard-swarm-master) run \
      -d \
      -ti \
      -p 8080:8080 \
      --restart=always \
      --link shipyard-rethinkdb:rethinkdb \
      -v $HOST_CERT_PATH:/etc/docker:ro \
      --name shipyard \
      $IMAGE server \
      --rethinkdb-addr=rethinkdb:28015 \
      -d tcp://$(docker-machine ip shipyard-swarm-master):3376 \
      --tls-ca-cert /etc/docker/ca.pem \
      --tls-cert /etc/docker/server.pem \
      --tls-key /etc/docker/server-key.pem \
      --auth-whitelist-cidr 127.0.0.0/8 $SHIPYARD_ARGS
}

if [ "$ACTION" = "install" ]; then
    echo "Deploying Shipyard using $PROVIDER..."
    TOKEN=`curl -XPOST https://discovery-stage.hub.docker.com/v1/clusters`

    docker-machine create -d $PROVIDER $MACHINE_ARGS --swarm --swarm-discovery token://$TOKEN --swarm-master shipyard-swarm-master
    
    docker $(docker-machine config shipyard-swarm-master) run \
        -d \
        --restart=always \
        --name shipyard-rethinkdb \
        shipyard/rethinkdb
    
    deploy_shipyard_controller

    SHIPYARD_IP=`docker-machine ip shipyard-swarm-master`
    
    echo "Shipyard v3 available at http://$SHIPYARD_IP:8080"
    echo "Username: admin Password: shipyard"
    
    echo "To remove, run docker-machine rm shipyard-swarm-master"

elif [ "$ACTION" = "node" ]; then
    echo "Adding node using $PROVIDER"
    ARGS="`docker $(docker-machine config shipyard-swarm-master) inspect --format='{{range $v := .Config.Cmd}} {{$v}} {{end}}' swarm-agent-master`"
    TOKEN=""
    for ARG in $ARGS; do
        if [[ $ARG == *"token://"* ]]; then
            TOKEN=$ARG
        fi
    done

    if [ -z "$TOKEN" ]; then
        echo "Unable to detect token"
        exit 1
    fi

    # get current number of nodes
    NODES=`docker-machine ls | grep shipyard-swarm-node | wc -l`
    NODE_NUM=$((NODES+1))
    NODE_NAME=shipyard-swarm-node-$PROVIDER-$NODE_NUM
    docker-machine create -d $PROVIDER $MACHINE_ARGS --swarm --swarm-discovery $TOKEN $NODE_NAME

    echo "Added node $NODE_NAME to cluster"
    echo "To remove, run docker-machine rm $NODE_NAME"

elif [ "$ACTION" = "upgrade" ]; then
    echo "Upgrading Shipyard"
    docker $(docker-machine config shipyard-swarm-master) pull $IMAGE

    docker $(docker-machine config shipyard-swarm-master) rm -fv shipyard

    deploy_shipyard_controller

    echo "Shipyard controller updated"

elif [ "$ACTION" = "destroy" ]; then
    NODES=`docker-machine ls -q | grep shipyard-swarm`

    if [ ! -z "$NODES" ]; then
        echo "Destroying Shipyard"
        echo $NODES | xargs docker-machine rm
        echo "Shipyard Removed"
    fi
else
    echo "Unknown action $ACTION"
    exit 1
fi
